### ISSUE TITLE
Nice tutorials!

### ISSUE THREAD

**Issue by jwkweon** [yklee1308/deep_learning#1]
Hello @yklee1308 ,
First of all, thank you for sharing this public code.

I think it would be helpful for research if you could upload more models in the future.

Thank you in advance.
Kweon

**Comment by yklee1308** [comment]
@jwkweon ,
Thank you for your interest in my repo.

I'll try to add more classification models in the future considering your feedback.

FYI, the goal of this project is to build a deep-learning framework that is well-structured and easy to understand at the same time.
This repo will be more helpful if you take a close look at the architecture and think about how it can be improved.
In addition, I'm planning to start new tasks like detection, segmentation and generation.

Please stay tuned!
